feat: updated to accept user specified mask
ngneat/falso pull request #105
Opened 2022-01-21 21:42 UTC by arulprabakaran

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2022-01-22 13:50 UTC, theryansmee requested changes

2022-01-22 13:50 UTC, theryansmee commented on packages/falso/src/lib/mask.ts
> +          return randomDigits.charAt(
This could just us `getRandomInRange({ min: 0, max: 9, fraction: 0 })` as you are already calling this function

2022-01-22 13:50 UTC, theryansmee commented on packages/falso/src/lib/mask.ts
> +          return randomChars.charAt(
Maybe this could use `randAlpha`

2022-01-22 16:51 UTC, NetanelBasal commented on packages/falso/src/lib/mask.ts
> +        if (item == char) return randAlpha();
Please change `==` to `===`

2022-01-23 07:59 UTC, arulprabakaran commented on packages/falso/src/lib/mask.ts
> +        if (item == char) return randAlpha();
Done @NetanelBasal

2022-01-23 08:07 UTC, merged